---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: usermgmt

outputs:
  - name: e2e-jar
run:
  path: usermgmt/ci/tasks/e2e-prepare.sh
  args: [
    --input-dir, usermgmt
    --output-dir, e2e-jar
  ]
