---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: usermgmt

outputs:
  - name: e2ejar
run:
  path: usermgmt/ci/tasks/e2e-prepare.sh
  args: [
    --input-dir, usermgmt
    --output-dir, e2ejar
  ]
