---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: elgalu/selenium

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: usermgmt

outputs:
  - name: build

run:
  path: usermgmt/ci/tasks/e2e.sh
  args: [
    --input-dir, usermgmt,
    --output-dir, build,
  ]
