---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: elgalu/selenium

inputs:
  - name: e2e-jar
  - name: usermgmt

outputs:
  - name: $VIDEO_PATH

run:
  path: usermgmt/ci/tasks/e2e.sh
  args: [
    --input-dir, e2e-jar,
    --output-dir, $VIDEO_PATH
  ]
