---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: elgalu/selenium

inputs:
  - name: e2e-jar
  - name: usermgmt

outputs:
  - name: e2e-video

run:
  path: usermgmt/ci/tasks/e2e.sh
  args: [
    --input-dir, usermgmt,
    --output-dir, e2e-video
  ]
