---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: elgalu/selenium

inputs:
  - name: usermgmt


run:
  path: usermgmt/ci/tasks/e2e.sh
  args: [
    --input-dir, usermgmt
  ]
