---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: usermgmt

run:
  path: usermgmt/ci/tasks/ui-unit.sh
  args: [
    --input-dir, usermgmt
  ]
