---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jhipster/jhipster

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: usermgmt

run:
  path: usermgmt/ci/tasks/unit.sh
  args: [
    --input-dir, usermgmt
  ]
